// Dashboard stats, expenses/recurring-expenses/budgets/owner-transactions (the
// accounting module), P&L, register report, and reconciliation.
import { getDb, query } from '../../db/client'
import { fullReports, registerReport, profitLossStatement } from '../../repositories/reports'
import { getReconciliation } from '../../repositories/reconciliation'
import { jsonResponse, body, dashboard, type RouteCtx } from '../shared'

export async function handleFinancialRoutes(ctx: RouteCtx): Promise<Response | null> {
  const { req, u, p, method, user } = ctx
    if(p==='/dashboard/stats' && method==='GET') return jsonResponse(await dashboard())
  if(p==='/expenses'&&method==='GET'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const db=await getDb();const sid=u.searchParams.get('registerSessionId');const from=u.searchParams.get('from');const to=u.searchParams.get('to');if(from||to){return jsonResponse({items:await (await import('../../services/expensesService')).listExpenses(from||undefined,to||undefined)})}return jsonResponse({items:query<any>(db,"SELECT e.*,u.name user_name FROM expenses e LEFT JOIN users u ON u.id=e.user_id WHERE (? IS NULL OR e.register_session_id=?) ORDER BY e.created_at DESC LIMIT 200",[sid,sid])})}
  if(p==='/expenses'&&method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);const sid=b.registerSessionId?String(b.registerSessionId):null;return jsonResponse(await (await import('../../services/expensesService')).addExpense({userId:user!.id,registerSessionId:sid,category:String(b.category||''),amount:Number(b.amount||0),note:b.note,expenseType:b.expenseType}),201)}
  if(p==='/recurring-expenses'&&method==='GET'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);return jsonResponse({items:await (await import('../../services/financialService')).listRecurringExpenses(u.searchParams.get('activeOnly')==='1')})}
  if(p==='/recurring-expenses'&&method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);return jsonResponse(await (await import('../../services/financialService')).addRecurringExpense({userId:user!.id,name:String(b.name||''),category:String(b.category||''),amount:Number(b.amount||0),frequency:b.frequency,dayOfMonth:Number(b.dayOfMonth||1),startDate:b.startDate,endDate:b.endDate,note:b.note}),201)}
  if(p.match(/^\/recurring-expenses\/[^/]+\/toggle$/)&&method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const id=p.split('/')[2];const b=await body(req);return jsonResponse(await (await import('../../services/financialService')).setRecurringExpenseActive(user!.id,id,!!b.active))}
  if(p.match(/^\/recurring-expenses\/[^/]+$/)&&method==='DELETE'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const id=p.split('/')[2];return jsonResponse(await (await import('../../services/financialService')).deleteRecurringExpense(user!.id,id))}
  if(p==='/recurring-expenses/generate-due'&&method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);return jsonResponse(await (await import('../../services/financialService')).generateDueRecurringExpenses(user!.id))}
  if(p==='/budgets'&&method==='GET'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const month=u.searchParams.get('month')||new Date().toISOString().slice(0,7);return jsonResponse({items:await (await import('../../services/financialService')).listBudgets(month)})}
  if(p==='/budgets'&&method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);return jsonResponse(await (await import('../../services/financialService')).setBudget(user!.id,{periodMonth:String(b.periodMonth||''),category:String(b.category||''),plannedAmount:Number(b.plannedAmount||0),note:b.note}),201)}
  if(p==='/reports/pnl'&&method==='GET'){if(user!.role==='cashier')return jsonResponse({error:'الكاشير لا يملك صلاحية التقارير'},403);await (await import('../../services/financialService')).generateDueRecurringExpenses(user!.id);return jsonResponse(await (await import('../../repositories/reports')).profitLossStatement(u.searchParams.get('from'),u.searchParams.get('to')))}
  if(p==='/owner-transactions'&&method==='GET'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);return jsonResponse(await (await import('../../services/ownerEquityService')).ownerLedger())}
  if(p==='/owner-transactions'&&method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);return jsonResponse(await (await import('../../services/ownerEquityService')).addOwnerTransaction({userId:user!.id,type:b.type==='withdrawal'?'withdrawal':'contribution',amount:Number(b.amount||0),date:b.date,note:b.note}),201)}
  if(p.match(/^\/owner-transactions\/[^/]+$/)&&method==='DELETE'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const id=p.split('/')[2];return jsonResponse(await (await import('../../services/ownerEquityService')).deleteOwnerTransaction(user!.id,id))}
  if(p==='/reports'&&method==='GET'){if(user!.role==='cashier')return jsonResponse({error:'الكاشير لا يملك صلاحية التقارير'},403);return jsonResponse(await fullReports(u.searchParams.get('from'),u.searchParams.get('to')))}
  if(p==='/reports/register'&&method==='GET'){if(user!.role==='cashier')return jsonResponse({error:'غير مصرح'},403);return jsonResponse({items:await registerReport(u.searchParams.get('from'),u.searchParams.get('to'))})}
  if(p==='/reconciliation'&&method==='GET'){if(user!.role==='cashier')return jsonResponse({error:'غير مصرح'},403);return jsonResponse(await getReconciliation())}

  return null
}
