// Customers, suppliers, their ledgers, and payments against their balances.
import { v4 as uuid } from 'uuid'
import { getDb, query, run } from '../../db/client'
import { recordCustomerPayment, recordSupplierPayment } from '../../repositories/payments'
import { jsonResponse, body, mapCustomer, mapSupplier, type RouteCtx } from '../shared'

export async function handlePartiesRoutes(ctx: RouteCtx): Promise<Response | null> {
  const { req, u, p, method, user } = ctx
  if(p==='/customers'&&method==='GET'&&u.searchParams.get('ledger')==='true'){const db=await getDb();const cid=u.searchParams.get('id')||u.searchParams.get('customerId');if(!cid)return jsonResponse({error:'العميل مطلوب'},400);return jsonResponse({items:query<any>(db,'SELECT * FROM customer_ledger WHERE customer_id=? ORDER BY created_at DESC',[cid])})}
  if(p==='/suppliers'&&method==='GET'&&u.searchParams.get('ledger')==='true'){const db=await getDb();const sid=u.searchParams.get('id')||u.searchParams.get('supplierId');if(!sid)return jsonResponse({error:'المورد مطلوب'},400);return jsonResponse({items:query<any>(db,'SELECT * FROM supplier_ledger WHERE supplier_id=? ORDER BY created_at DESC',[sid])})}
  if(p==='/customer-payments' && method==='GET'){ const db=await getDb(); const cid=u.searchParams.get('customerId'); return jsonResponse({items:query<any>(db,'SELECT cp.*,s.invoice_no invoiceNo FROM customer_payments cp LEFT JOIN sales s ON s.id=cp.sale_id WHERE (? IS NULL OR cp.customer_id=?) ORDER BY cp.date DESC LIMIT 100',[cid,cid])}) }
  const cust=p.match(/^\/customers\/([^/]+)$/); if(cust){ const id=cust[1],db=await getDb(); if(method==='GET'){const r=query<any>(db,'SELECT * FROM customers WHERE id=?',[id])[0]; return r?jsonResponse(mapCustomer(r)):jsonResponse({error:'غير موجود'},404)} if(method==='PATCH'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req); if(!String(b.name||'').trim())return jsonResponse({error:'اسم العميل مطلوب'},400); run(db,"UPDATE customers SET name=?,phone=?,address=?,notes=?,updated_at=datetime('now') WHERE id=?",[b.name,b.phone||null,b.address||null,b.notes||null,id]);await (await import('../../db/client')).persist();return jsonResponse(mapCustomer(query<any>(db,'SELECT * FROM customers WHERE id=?',[id])[0]))} if(method==='DELETE'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);if(query(db,'SELECT 1 FROM sales WHERE customer_id=? LIMIT 1',[id]).length)return jsonResponse({error:'لا يمكن حذف عميل مرتبط بفواتير'},400);run(db,'DELETE FROM customers WHERE id=?',[id]);await (await import('../../db/client')).persist();return jsonResponse({success:true})}}
  const sup=p.match(/^\/suppliers\/([^/]+)$/); if(sup){ const id=sup[1],db=await getDb(); if(method==='GET'){const r=query<any>(db,'SELECT * FROM suppliers WHERE id=?',[id])[0];return r?jsonResponse(mapSupplier(r)):jsonResponse({error:'غير موجود'},404)} if(method==='PATCH'){const b=await body(req); if(!String(b.name||'').trim())return jsonResponse({error:'اسم المورد مطلوب'},400); run(db,"UPDATE suppliers SET name=?,phone=?,address=?,notes=?,updated_at=datetime('now') WHERE id=?",[b.name,b.phone||null,b.address||null,b.notes||null,id]);await (await import('../../db/client')).persist();return jsonResponse(mapSupplier(query<any>(db,'SELECT * FROM suppliers WHERE id=?',[id])[0]))} if(method==='DELETE'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);if(query(db,'SELECT 1 FROM purchases WHERE supplier_id=? LIMIT 1',[id]).length)return jsonResponse({error:'لا يمكن حذف مورد مرتبط بفواتير'},400);run(db,'DELETE FROM suppliers WHERE id=?',[id]);await (await import('../../db/client')).persist();return jsonResponse({success:true})}}
  if(p==='/customers' && method==='GET'){const db=await getDb(); return jsonResponse(query<any>(db,`SELECT c.*,COALESCE((SELECT SUM(total) FROM sales s WHERE s.customer_id=c.id AND s.status!='voided'),0) totalPurchases,COALESCE((SELECT SUM(amount) FROM customer_payments cp WHERE cp.customer_id=c.id),0) totalPaid FROM customers c ORDER BY c.name`))}
  if(p==='/customers' && method==='POST'){const b=await body(req);const name=String(b.name||'').trim();if(!name)return jsonResponse({error:'اسم العميل مطلوب'},400);const db=await getDb();const id=uuid();run(db,'INSERT INTO customers(id,name,phone,address,notes) VALUES(?,?,?,?,?)',[id,name,b.phone||null,b.address||null,b.notes||null]);run(db,'INSERT INTO audit_logs(id,user_id,action,entity,entity_id,after_json) VALUES(?,?,?,?,?,?)',[uuid(),user!.id,'CREATE','customer',id,JSON.stringify({name,phone:b.phone||null})]);await (await import('../../db/client')).persist();return jsonResponse({id,name,phone:b.phone||null,address:b.address||null,notes:b.notes||null,balance:0,loyaltyPoints:0},201)}
  const cm=p.match(/^\/customers\/([^/]+)$/); if(cm){const id=cm[1];const db=await getDb();if(method==='PATCH'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);run(db,'UPDATE customers SET name=?,phone=?,address=?,notes=?,updated_at=datetime(\'now\') WHERE id=?',[b.name,b.phone||null,b.address||null,b.notes||null,id]);await (await import('../../db/client')).persist();return jsonResponse({ok:true})}if(method==='DELETE'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);run(db,'DELETE FROM customers WHERE id=?',[id]);await (await import('../../db/client')).persist();return jsonResponse({ok:true})}}
  if(p==='/suppliers' && method==='GET'){const db=await getDb();return jsonResponse(query<any>(db,'SELECT * FROM suppliers ORDER BY name').map((r:any)=>({...r,phone:r.phone||null})))}
  if(p==='/suppliers' && method==='POST'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);const db=await getDb();const id=uuid();run(db,'INSERT INTO suppliers(id,name,phone,address,notes) VALUES(?,?,?,?,?)',[id,b.name,b.phone||null,b.address||null,b.notes||null]);await (await import('../../db/client')).persist();return jsonResponse({id,name:b.name,phone:b.phone||null,address:b.address||null,notes:b.notes||null,balance:0},201)}
  const sm=p.match(/^\/suppliers\/([^/]+)$/);if(sm){const id=sm[1];const db=await getDb();if(method==='PATCH'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);const b=await body(req);run(db,'UPDATE suppliers SET name=?,phone=?,address=?,notes=?,updated_at=datetime(\'now\') WHERE id=?',[b.name,b.phone||null,b.address||null,b.notes||null,id]);await (await import('../../db/client')).persist();return jsonResponse({ok:true})}if(method==='DELETE'){if(!['admin','manager'].includes(user!.role))return jsonResponse({error:'صلاحية غير كافية'},403);run(db,'DELETE FROM suppliers WHERE id=?',[id]);await (await import('../../db/client')).persist();return jsonResponse({ok:true})}}
  if(p==='/customer-payments'&&method==='POST'){const b=await body(req); const idem=b.idempotencyKey || req.headers.get('Idempotency-Key') || undefined; const db=await getDb(); if(idem){const prior=query<any>(db,'SELECT id FROM customer_payments WHERE idempotency_key=? LIMIT 1',[idem])[0]; if(prior)return jsonResponse(prior)} const rs=b.registerSessionId||query<any>(db,"SELECT id FROM register_sessions WHERE user_id=? AND status='open' ORDER BY opened_at DESC LIMIT 1",[user!.id])[0]?.id||null; return jsonResponse(await recordCustomerPayment({userId:user!.id,customerId:b.customerId,amount:Number(b.amount),method:b.method||'cash',notes:b.notes,registerSessionId:rs,idempotencyKey:idem}))}
  if(p==='/supplier-payments'&&method==='GET'){const db=await getDb();const sid=u.searchParams.get('supplierId');return jsonResponse({items:query<any>(db,'SELECT sp.*,pu.invoice_no FROM supplier_payments sp LEFT JOIN purchases pu ON pu.id=sp.purchase_id WHERE (? IS NULL OR sp.supplier_id=?) ORDER BY sp.date DESC LIMIT 100',[sid,sid]).map((r:any)=>({...r,purchase:r.invoice_no?{invoiceNo:r.invoice_no}:null}))})}
  if(p==='/supplier-payments'&&method==='POST'){const b=await body(req);b.idempotencyKey=b.idempotencyKey || req.headers.get('Idempotency-Key') || undefined;const db=await getDb(); if(b.idempotencyKey){const prior=query<any>(db,'SELECT id FROM supplier_payments WHERE idempotency_key=? LIMIT 1',[b.idempotencyKey])[0]; if(prior)return jsonResponse(prior)} const rs=b.registerSessionId||query<any>(db,"SELECT id FROM register_sessions WHERE user_id=? AND status='open' ORDER BY opened_at DESC LIMIT 1",[user!.id])[0]?.id||null; return jsonResponse(await recordSupplierPayment({userId:user!.id,supplierId:b.supplierId,amount:Number(b.amount),method:b.method||'cash',notes:b.notes,registerSessionId:rs,idempotencyKey:b.idempotencyKey}))}

  return null
}
