'use client'

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Skeleton } from '@/components/ui/skeleton'
import { Plus, ShoppingCart, Eye, Trash2, Minus, PackageSearch, Truck, Wallet, X, Check, Calculator, Banknote, Printer, Search as SearchIcon } from 'lucide-react'
import { toast } from 'sonner'
import { formatEGP, formatDateTime } from '@/lib/format'
import { EmptyState } from '@/components/empty-state'
import { PrintPreviewDialog } from '@/components/print-preview-dialog'
import { unitLabel } from '@/lib/units'

interface Variant { id: string; sku: string; size: string | null; color: string | null; costPrice: number; quantity: number; purchaseUnit?: string; purchaseUnitFactor?: number; baseUnit?: string; product: { name: string } }
interface Supplier { id: string; name: string; balance: number }
interface Purchase { id: string; invoiceNo: string; date: string; subtotal: number; discount: number; taxAmount: number; total: number; paid: number; status: string; notes?: string | null; supplier?: { name: string }; items?: { id: string; variantId: string; quantity: number; unitCost: number; total: number; enteredQuantity?: number | null; unit?: string | null; unitFactor?: number | null; variant: { sku: string; size: string | null; color: string | null; product: { name: string } } }[] | null }
interface LineItem { variantId: string; quantity: number; unitCost: number; enteredQuantity: number; unit: string; unitFactor: number }

const QUICK_AMOUNTS = [0, 100, 200, 500, 1000, 2000]
function money(n: number) { return `${formatEGP(n)} ج.م` }
function clampMoney(n: number) { return Math.max(0, Math.round((Number(n) || 0) * 100) / 100) }

function TouchNumberPad({ value, onChange, onDone }: { value: number; onChange: (n: number) => void; onDone?: () => void }) {
  const [raw, setRaw] = useState(String(value || ''))
  function press(k: string) {
    let next = raw
    if (k === 'clear') next = ''
    else if (k === 'back') next = raw.slice(0, -1)
    else if (k === '.') next = raw.includes('.') ? raw : `${raw || '0'}.`
    else next = raw === '0' ? k : raw + k
    setRaw(next)
    onChange(clampMoney(Number(next) || 0))
  }
  return <div className="rounded-3xl border bg-muted/20 p-3 select-none touch-manipulation">
    <div className="mb-3 flex h-14 items-center justify-between rounded-2xl bg-background px-4 text-2xl font-black tabular-nums"><span>{raw || '0'}</span><span className="text-sm font-semibold text-muted-foreground">ج.م</span></div>
    <div className="grid grid-cols-3 gap-2">
      {['1','2','3','4','5','6','7','8','9','.','0','back'].map(k => <Button key={k} type="button" variant="outline" className="h-14 rounded-2xl text-xl font-black" onClick={() => press(k)}>{k === 'back' ? '⌫' : k}</Button>)}
    </div>
    <div className="mt-2 grid grid-cols-2 gap-2"><Button type="button" variant="outline" className="h-12 rounded-2xl" onClick={() => press('clear')}>مسح</Button><Button type="button" className="h-12 rounded-2xl" onClick={onDone}><Check className="me-1"/> تم</Button></div>
  </div>
}

export function PurchasesSection() {
  const qc = useQueryClient()
  const [search, setSearch] = useState('')
  const [supplierFilter, setSupplierFilter] = useState('all')
  const [statusFilter, setStatusFilter] = useState('all')
  const [fromDate, setFromDate] = useState('')
  const [toDate, setToDate] = useState('')
  const [open, setOpen] = useState(false)
  const [viewing, setViewing] = useState<Purchase | null>(null)
  const [supplierId, setSupplierId] = useState('')
  const [discount, setDiscount] = useState(0)
  const [paid, setPaid] = useState(0)
  const [paymentMethod, setPaymentMethod] = useState('cash')
  const [notes, setNotes] = useState('')
  const [items, setItems] = useState<LineItem[]>([])
  const [productFilter, setProductFilter] = useState('')
  const [moneyEditor, setMoneyEditor] = useState<'discount'|'paid'|'price'|'qty'|null>(null)
  const [editingLine, setEditingLine] = useState<number | null>(null)
  const [printPreview, setPrintPreview] = useState<{title:string;html:string}|null>(null)

  const { data: purchasesData, isLoading } = useQuery<{ items: Purchase[] }>({ queryKey: ['purchases'], queryFn: async () => (await fetch('/api/purchases?pageSize=100')).json() })
  const purchases = Array.isArray(purchasesData?.items) ? purchasesData.items : []
  const { data: productsData } = useQuery<{ items: { id: string; name: string; variants: Variant[] }[] }>({ queryKey: ['products-for-purchases'], queryFn: async () => (await fetch('/api/products?pageSize=500')).json() })
  const { data: suppliers = [] } = useQuery<Supplier[]>({ queryKey: ['suppliers'], queryFn: async () => (await fetch('/api/suppliers')).json() })
  const allVariants = useMemo(() => (Array.isArray(productsData?.items) ? productsData.items : []).flatMap(p => (Array.isArray(p.variants) ? p.variants : []).map(v => ({ ...v, productName: p.name }))), [productsData])
  const products = useMemo(() => {
    const q = productFilter.trim().toLowerCase()
    return allVariants.filter(v => !q || v.productName.toLowerCase().includes(q) || v.sku.toLowerCase().includes(q)).slice(0, 60)
  }, [allVariants, productFilter])
  const filteredPurchases = purchases.filter(p => { const q=search.trim().toLowerCase(); const okSearch=!q||p.invoiceNo.toLowerCase().includes(q)||String(p.supplier?.name||'').toLowerCase().includes(q); const okSupplier=supplierFilter==='all'||p.supplier?.name===supplierFilter; const okStatus=statusFilter==='all'||p.status===statusFilter; const d=String(p.date||'').slice(0,10); const okFrom=!fromDate||d>=fromDate; const okTo=!toDate||d<=toDate; return okSearch&&okSupplier&&okStatus&&okFrom&&okTo })
  const subtotal = items.reduce((s, i) => s + i.enteredQuantity * i.unitCost, 0)
  const total = Math.max(0, subtotal - discount)
  const remaining = Math.max(0, total - paid)

  const createMutation = useMutation({ mutationFn: async (data: any) => { const r = await fetch('/api/purchases', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!r.ok) throw new Error((await r.json()).error || 'فشل حفظ الفاتورة'); return r.json() }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['purchases'] }); qc.invalidateQueries({ queryKey: ['products'] }); qc.invalidateQueries({ queryKey: ['suppliers'] }); qc.invalidateQueries({ queryKey: ['dashboard-stats'] }); toast.success('تم تسجيل فاتورة الشراء وتحديث المخزون'); setOpen(false); reset() }, onError: (e: Error) => toast.error(e.message) })
  const voidMutation = useMutation({ mutationFn: async (purchaseId: string) => { const r = await fetch(`/api/purchases/${purchaseId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'void', voidReason: 'إلغاء من شاشة المشتريات' }) }); if (!r.ok) throw new Error((await r.json()).error || 'فشل إلغاء الفاتورة'); return r.json() }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['purchases'] }); qc.invalidateQueries({ queryKey: ['products'] }); qc.invalidateQueries({ queryKey: ['suppliers'] }); toast.success('تم إلغاء فاتورة الشراء وإرجاع المخزون'); setViewing(null) }, onError: (e: Error) => toast.error(e.message) })
  function reset() { setSupplierId(''); setDiscount(0); setPaid(0); setPaymentMethod('cash'); setNotes(''); setItems([]); setProductFilter(''); setMoneyEditor(null); setEditingLine(null) }
  function add(v: any) { if (items.some(i => i.variantId === v.id)) return toast.info('الصنف موجود بالفعل'); const unit = v.purchaseUnit || 'piece'; const factor = Number(v.purchaseUnitFactor) || 1; setItems([...items, { variantId: v.id, quantity: factor, enteredQuantity: 1, unitCost: (v.costPrice || 0) * factor, unit, unitFactor: factor }]); }
  function update(i: number, patch: Partial<LineItem>) { setItems(items.map((x, idx) => idx === i ? { ...x, ...patch } : x)) }
  function remove(i: number) { setItems(items.filter((_, idx) => idx !== i)) }
  function submit() { if (!supplierId) return toast.error('اختر المورد'); if (!items.length) return toast.error('أضف صنفًا واحدًا على الأقل'); if (items.some(i => i.enteredQuantity <= 0 || i.unitCost <= 0)) return toast.error('راجع الكميات والأسعار'); if (paid > total) return toast.error('المدفوع أكبر من الإجمالي'); createMutation.mutate({ supplierId, discount: Number(discount) || 0, paid: Number(paid) || 0, paymentMethod, notes, status: 'completed', items: items.map(i => ({ variantId: i.variantId, quantity: i.quantity, unitCost: i.unitCost, enteredQuantity: i.enteredQuantity, unit: i.unit, unitFactor: i.unitFactor })) }) }

  function printPurchase(p: Purchase) {
    const win=window.open('','_blank','width=900,height=900'); if(!win)return toast.error('اسمح بفتح نافذة الطباعة')
    const rows=(p.items||[]).map(it=>`<tr><td>${it.variant.product.name}<div class="muted">${it.variant.sku}${it.variant.size?` · ${it.variant.size}`:''}${it.variant.color?` · ${it.variant.color}`:''}</div></td><td>${it.enteredQuantity||it.quantity} ${unitLabel(it.unit||'piece')}</td><td>${money(it.unitCost)}</td><td>${money(it.total)}</td></tr>`).join('')
    win.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>فاتورة شراء ${p.invoiceNo}</title><style>body{font-family:Arial;margin:0;padding:24px}.sheet{max-width:800px;margin:auto}.head{text-align:center;border-bottom:1px dashed #999;padding-bottom:14px}.title{font-size:24px;font-weight:800}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:8px;border-bottom:1px solid #eee;text-align:right;font-size:13px}th{background:#f4f4f4}.muted{font-size:10px;color:#777;margin-top:3px}.totals{margin-top:18px;margin-right:auto;width:280px}.row{display:flex;justify-content:space-between;padding:6px 0}@media print{@page{margin:8mm}body{padding:0}.sheet{max-width:none}}</style></head><body><div class="sheet"><div class="head"><div class="title">KAYAN</div><div>فاتورة شراء</div><div style="font-size:12px;color:#666">${p.invoiceNo} · ${formatDateTime(p.date)} · المورد: ${p.supplier?.name||'—'}</div></div><table><thead><tr><th>الصنف</th><th>الكمية</th><th>سعر التكلفة</th><th>الإجمالي</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div class="row"><span>الخصم</span><b>${money(p.discount)}</b></div><div class="row"><span>الضريبة</span><b>${money(p.taxAmount)}</b></div><div class="row" style="font-size:17px;font-weight:800;border-top:1px solid #222;padding-top:10px"><span>الإجمالي</span><b>${money(p.total)}</b></div><div class="row"><span>المدفوع</span><b>${money(p.paid)}</b></div><div class="row"><span>المتبقي</span><b>${money(Math.max(0,p.total-p.paid))}</b></div></div></div><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),500)}</script></body></html>`);win.document.close()
  }

  return <div className="space-y-4 pb-28">
    <div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">فواتير الشراء</h2><p className="text-sm text-muted-foreground">Touch First · شراء → مخزون → حساب المورد</p></div><Button className="h-14 rounded-2xl px-5 text-base font-bold" onClick={() => { reset(); setOpen(true) }}><Plus className="me-2"/> فاتورة شراء</Button></div>
    <Card><CardContent className="p-3"><div className="grid gap-2 md:grid-cols-6"><div className="relative md:col-span-2"><SearchIcon className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم الفاتورة / المورد" className="h-11 w-full rounded-xl border bg-background px-9 text-right text-sm"/></div><select value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)} className="h-11 rounded-xl border bg-background px-3"><option value="all">كل الموردين</option>{(Array.isArray(suppliers)?suppliers:[]).map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="h-11 rounded-xl border bg-background px-3"><option value="all">كل الحالات</option><option value="completed">مكتملة</option><option value="voided">ملغاة</option></select><Input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="h-11"/><Input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} className="h-11"/></div></CardContent></Card>
    {isLoading ? <div className="space-y-2">{Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-16 rounded-2xl"/>)}</div> : filteredPurchases.length === 0 ? <EmptyState title="لا توجد فواتير شراء" description="غيّر البحث أو الفلاتر أو أنشئ فاتورة جديدة" icon={ShoppingCart}/> : <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/40"><th className="p-3 text-right">الفاتورة</th><th className="p-3 text-right">التاريخ</th><th className="p-3 text-right">المورد</th><th className="p-3 text-right">الأصناف</th><th className="p-3 text-right">الإجمالي</th><th className="p-3 text-right">المدفوع</th><th className="p-3 text-right">المتبقي</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">إجراء</th></tr></thead><tbody>{filteredPurchases.map(p=>{const rem=Math.max(0,p.total-p.paid);return <tr key={p.id} className="border-b hover:bg-muted/20"><td className="p-3 font-bold">{p.invoiceNo}</td><td className="p-3 whitespace-nowrap">{formatDateTime(p.date)}</td><td className="p-3">{p.supplier?.name||'بدون مورد'}</td><td className="p-3">{p.items?.length||0}</td><td className="p-3 font-bold">{money(p.total)}</td><td className="p-3">{money(p.paid)}</td><td className="p-3">{money(rem)}</td><td className="p-3"><Badge variant={p.status==='voided'?'destructive':rem>0?'outline':'default'}>{p.status==='voided'?'ملغاة':rem>0?'متبقي':'مدفوعة'}</Badge></td><td className="p-3"><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setViewing(p)}><Eye className="me-1 size-4"/>عرض</Button><Button variant="outline" size="sm" onClick={()=>printPurchase(p)}><Printer className="me-1 size-4"/>طباعة</Button></div></td></tr>})}</tbody></table></div></CardContent></Card>}

    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="h-[100dvh] w-screen max-w-none rounded-none p-0 overflow-hidden sm:h-[96dvh] sm:w-[calc(100vw-2rem)] sm:max-w-6xl sm:rounded-3xl"><div className="flex h-full min-h-0 flex-col bg-background">
      <div className="shrink-0 border-b px-4 py-4"><div className="flex items-center justify-between"><div><DialogTitle className="text-xl font-black">فاتورة شراء جديدة</DialogTitle><DialogDescription>كل خطوات الفاتورة باللمس — بدون لوحة مفاتيح</DialogDescription></div><Button variant="outline" size="icon" className="size-11 rounded-2xl" onClick={() => setOpen(false)}><X/></Button></div></div>
      <div className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-5"><div className="grid gap-4 lg:grid-cols-[1.35fr_.95fr]">
        <div className="space-y-4">
          <section className="rounded-3xl border p-3 sm:p-4"><div className="mb-3 flex items-center gap-2"><Truck className="size-5 text-primary"/><h3 className="font-black">1 · اختر المورد</h3></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{(Array.isArray(suppliers) ? suppliers : []).map(s => <button key={s.id} type="button" onClick={() => setSupplierId(s.id)} className={`min-h-20 rounded-2xl border p-3 text-right transition active:scale-[.98] ${supplierId === s.id ? 'border-primary bg-primary/10 ring-2 ring-primary/20' : 'bg-card'}`}><div className="font-bold">{s.name}</div><div className="mt-1 text-xs text-muted-foreground">{s.balance > 0 ? `عليه ${money(s.balance)}` : 'حسابه سليم'}</div></button>)}</div>{!suppliers.length && <div className="rounded-2xl bg-muted/40 p-4 text-center text-sm text-muted-foreground">أضف موردًا أولاً</div>}</section>

          <section className="rounded-3xl border p-3 sm:p-4"><div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><PackageSearch className="size-5 text-primary"/><h3 className="font-black">2 · أضف الأصناف</h3></div><Badge variant="outline">{items.length} صنف</Badge></div><div className="mb-3 grid grid-cols-3 gap-2"><Button type="button" variant={!productFilter ? 'default' : 'outline'} className="h-11 rounded-2xl" onClick={() => setProductFilter('')}>الكل</Button><Button type="button" variant={productFilter === 'مقاس' ? 'default' : 'outline'} className="h-11 rounded-2xl" onClick={() => setProductFilter('مقاس')}>مقاسات</Button><Button type="button" variant={productFilter === 'لون' ? 'default' : 'outline'} className="h-11 rounded-2xl" onClick={() => setProductFilter('لون')}>ألوان</Button></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{products.map(v => <button key={v.id} type="button" onClick={() => add(v)} className={`min-h-28 rounded-2xl border p-3 text-right transition active:scale-[.98] ${items.some(i => i.variantId === v.id) ? 'border-emerald-500 bg-emerald-50/60 dark:bg-emerald-950/20' : 'bg-card hover:bg-muted/40'}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="font-bold leading-tight">{v.productName}</div><div className="mt-1 text-xs text-muted-foreground">{v.size || 'مقاس عام'}{v.color ? ` · ${v.color}` : ''}</div></div>{items.some(i => i.variantId === v.id) && <Check className="size-5 shrink-0 text-emerald-600"/>}</div><div className="mt-3 text-xs text-primary">{unitLabel(v.purchaseUnit || 'piece')} × {v.purchaseUnitFactor || 1}</div><div className="mt-1 text-sm font-black">{money((v.costPrice || 0) * (v.purchaseUnitFactor || 1))}</div></button>)}</div></section>

        </div>

        <aside className="lg:sticky lg:top-0 lg:h-fit"><Card className="rounded-3xl border-2 overflow-hidden"><CardContent className="p-0"><div className="border-b bg-muted/30 p-4"><div className="flex items-center gap-2"><Calculator className="size-5 text-primary"/><h3 className="font-black">ملخص الفاتورة</h3></div></div><div className="space-y-3 p-4"><div className="flex justify-between"><span>قبل الخصم</span><b>{money(subtotal)}</b></div><button type="button" className="flex w-full items-center justify-between rounded-2xl border p-3 text-right" onClick={() => setMoneyEditor('discount')}><span>الخصم</span><b>{money(discount)}</b></button><div className="flex items-center justify-between rounded-2xl bg-primary/10 p-4"><span className="font-bold">الصافي</span><b className="text-2xl font-black">{money(total)}</b></div><button type="button" className="flex w-full items-center justify-between rounded-2xl border p-3 text-right" onClick={() => setMoneyEditor('paid')}><span className="flex items-center gap-2"><Banknote className="size-5"/> المدفوع</span><b>{money(paid)}</b></button><div className="rounded-2xl bg-muted/50 p-3"><div className="flex justify-between text-sm"><span>المتبقي للمورد</span><b>{money(remaining)}</b></div></div><div><div className="mb-2 text-sm font-bold">طريقة الدفع</div><div className="grid grid-cols-3 gap-2">{[['cash','💵 نقدي'],['card','💳 بطاقة'],['transfer','🔄 تحويل']].map(([id,label]) => <button key={id} type="button" onClick={() => setPaymentMethod(id)} className={`h-14 rounded-2xl border text-sm font-bold ${paymentMethod === id ? 'border-primary bg-primary/10 ring-2 ring-primary/20' : ''}`}>{label}</button>)}</div></div><button type="button" className="h-12 w-full rounded-2xl border p-3 text-right text-sm" onClick={() => setNotes(notes ? '' : 'تمت المراجعة')}>📝 {notes || 'إضافة ملاحظة'}</button>

          <div className="space-y-2 border-t pt-3"><div className="flex items-center gap-2 px-1"><ShoppingCart className="size-5 text-primary"/><h3 className="font-black">الأصناف داخل الفاتورة</h3></div>{items.length === 0 ? <Card className="rounded-3xl border-dashed"><CardContent className="py-8 text-center text-muted-foreground">اضغط على أي صنف لإضافته</CardContent></Card> : <div className="max-h-[34vh] space-y-2 overflow-y-auto">{items.map((it, i) => { const v = allVariants.find(x => x.id === it.variantId); const lineTotal = it.enteredQuantity * it.unitCost; const perPieceCost = it.unitCost / (it.unitFactor || 1); return <Card key={it.variantId} className="rounded-2xl overflow-hidden"><CardContent className="p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-base font-black">{v?.productName || 'منتج'}</div><div className="text-xs text-muted-foreground">{v?.size || 'مقاس عام'}{v?.color ? ` · ${v.color}` : ''} · {v?.sku}</div></div><Button variant="outline" size="icon" className="size-9 rounded-xl text-destructive" onClick={() => remove(i)}><Trash2 className="size-4"/></Button></div>
            <div className="mt-2"><div className="mb-1.5 text-[10px] text-muted-foreground">وحدة الشراء</div><div className="grid grid-cols-4 gap-1.5">{([['piece','قطعة',1],['quarter-dozen','ربع دستة',3],['half-dozen','نص دستة',6],['dozen','دستة',12]] as const).map(([code,label,factor]) => <button key={code} type="button" onClick={() => { const newFactor = factor; const newCost = Math.round(perPieceCost * newFactor * 100) / 100; update(i, { unit: code, unitFactor: newFactor, unitCost: newCost, quantity: it.enteredQuantity * newFactor }) }} className={`rounded-xl border py-2 text-[10px] font-black active:scale-[.98] ${it.unitFactor === factor ? 'border-primary bg-primary/10 text-primary' : 'bg-card text-muted-foreground'}`}>{label}</button>)}</div></div>
            <div className="mt-2 grid grid-cols-2 gap-2"><div className="rounded-xl bg-muted/40 p-2"><div className="mb-1 text-center text-[10px] text-muted-foreground">الكمية ({unitLabel(it.unit)})</div><div className="flex h-10 items-center"><Button type="button" variant="outline" className="size-9 shrink-0 rounded-lg" onClick={() => { const q = Math.max(1, it.enteredQuantity - 1); update(i, { enteredQuantity: q, quantity: q * it.unitFactor }) }}><Minus className="size-3.5"/></Button><button type="button" className="flex-1 text-center text-base font-black tabular-nums active:opacity-60" onClick={() => { setEditingLine(i); setMoneyEditor('qty') }}>{it.enteredQuantity}</button><Button type="button" variant="outline" className="size-9 shrink-0 rounded-lg" onClick={() => { const q = it.enteredQuantity + 1; update(i, { enteredQuantity: q, quantity: q * it.unitFactor }) }}><Plus className="size-3.5"/></Button></div></div><button type="button" className="rounded-xl border p-2 text-right active:scale-[.99]" onClick={() => { setEditingLine(i); setMoneyEditor('price') }}><div className="text-[10px] text-muted-foreground">سعر {unitLabel(it.unit)}</div><div className="mt-1 text-sm font-black">{money(it.unitCost)}</div></button></div>
            <div className="mt-2 rounded-xl bg-primary/5 p-2"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">إجمالي البند</span><span className="text-sm font-black">{money(lineTotal)}</span></div></div>
          </CardContent></Card>})}</div>}</div></div></CardContent></Card></aside>
      </div></div>
      <div className="shrink-0 border-t bg-background p-3"><div className="mx-auto flex max-w-6xl gap-2"><Button variant="outline" className="h-14 flex-1 rounded-2xl text-base" onClick={() => setOpen(false)}>إلغاء</Button><Button className="h-14 flex-[2] rounded-2xl text-base font-black" onClick={submit} disabled={createMutation.isPending || !items.length || !supplierId}><Wallet className="me-2"/>{createMutation.isPending ? 'جاري الحفظ...' : `حفظ الفاتورة · ${money(total)}`}</Button></div></div>
    </div></DialogContent></Dialog>

    <Dialog open={!!moneyEditor} onOpenChange={() => { setMoneyEditor(null); setEditingLine(null) }}><DialogContent className="w-[calc(100vw-1rem)] max-w-md rounded-3xl p-4"><DialogHeader><DialogTitle>{moneyEditor === 'price' ? 'تعديل سعر الوحدة' : moneyEditor === 'qty' ? 'إدخال الكمية' : moneyEditor === 'discount' ? 'إدخال الخصم' : 'إدخال المدفوع'}</DialogTitle><DialogDescription>لوحة أرقام Touch — لا تحتاج لوحة مفاتيح الجهاز</DialogDescription></DialogHeader><TouchNumberPad value={moneyEditor === 'price' && editingLine !== null ? items[editingLine]?.unitCost || 0 : moneyEditor === 'qty' && editingLine !== null ? items[editingLine]?.enteredQuantity || 0 : moneyEditor === 'discount' ? discount : paid} onChange={n => { if (moneyEditor === 'price' && editingLine !== null) update(editingLine, { unitCost: n }); else if (moneyEditor === 'qty' && editingLine !== null) { const q = Math.max(1, Math.round(n)); update(editingLine, { enteredQuantity: q, quantity: q * items[editingLine].unitFactor }) } else if (moneyEditor === 'discount') setDiscount(n); else if (moneyEditor === 'paid') setPaid(n) }} onDone={() => { setMoneyEditor(null); setEditingLine(null) }}/></DialogContent></Dialog>

    <Dialog open={!!viewing} onOpenChange={() => setViewing(null)}><DialogContent className="w-[calc(100vw-1rem)] max-w-2xl rounded-3xl"><DialogHeader><DialogTitle className="flex items-center gap-2">فاتورة {viewing?.invoiceNo}{viewing?.status === 'voided' && <Badge variant="destructive">ملغاة</Badge>}</DialogTitle><DialogDescription>{viewing?.supplier?.name} · {viewing && formatDateTime(viewing.date)}</DialogDescription></DialogHeader>{viewing && <div className="max-h-[60vh] space-y-2 overflow-y-auto">{(viewing.items || []).map(it => <div key={it.id} className="rounded-2xl border p-3"><div className="font-bold">{it.variant.product.name}</div><div className="text-xs text-muted-foreground">{it.variant.sku}{it.variant.size ? ` · ${it.variant.size}` : ''}{it.variant.color ? ` · ${it.variant.color}` : ''}</div><div className="mt-2 flex justify-between text-sm"><span>{it.enteredQuantity || it.quantity} {unitLabel(it.unit || 'piece')}</span><b>{money(it.total)}</b></div></div>)}<Button variant="outline" className="h-11 w-full rounded-2xl" onClick={()=>printPurchase(viewing)}><Printer className="me-2 size-4"/>طباعة فاتورة الشراء</Button><div className="rounded-2xl bg-muted/50 p-4"><div className="flex justify-between"><span>الإجمالي</span><b>{money(viewing.total)}</b></div><div className="mt-1 flex justify-between"><span>المدفوع</span><b>{money(viewing.paid)}</b></div><div className="mt-1 flex justify-between"><span>المتبقي</span><b>{money(Math.max(0, viewing.total - viewing.paid))}</b></div></div>{viewing.status === 'completed' && <Button variant="destructive" className="h-12 w-full rounded-2xl" disabled={voidMutation.isPending} onClick={() => { if (confirm('هل تريد إلغاء فاتورة الشراء دي؟ هيتم رجوع المخزون اللي دخل بيها.')) voidMutation.mutate(viewing.id) }}><Trash2 className="me-2 size-4"/> {voidMutation.isPending ? 'جاري الإلغاء...' : 'إلغاء الفاتورة'}</Button>}</div>}</DialogContent></Dialog>
  </div>
}
