'use client'

import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { BarChart3, Download, FileSpreadsheet, Printer, RefreshCw, TrendingUp, Package, WalletCards, type LucideIcon } from 'lucide-react'
import { formatEGP, todayISO, daysAgoISO, paymentMethodLabel } from '@/lib/format'
import { toast } from 'sonner'
import { PrintPreviewDialog } from '@/components/print-preview-dialog'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

function money(v:number | null | undefined){return `${formatEGP(Number(v||0))} ج.م`}

type Tab='overview'|'sales'|'products'|'inventory'|'finance'
interface Report {
 from:string;to:string;salesCount:number;totalUnits:number;totalSales:number;netSales:number;totalReturns:number;totalPurchases:number;cogs:number;grossProfit:number;totalExpenses:number;netProfit:number;profitMargin:number;grossMargin:number;
 bestSelling:Array<{id:string;name:string;sku:string;qty:number;revenue:number;profit:number}>;
 salesByCategory:Array<{name:string;value:number}>; salesByMethod:Array<{name:string;value:number}>;
 dailyTrend:Array<{date:string;sales:number;profit:number;purchases:number;returns:number}>;
 expensesByCategory:Array<{category:string;type:string;total:number;count:number}>;
 inventory:{cost_value:number;retail_value:number;potential_profit:number;variants:number;low_stock:number;out_of_stock:number};customerBalance:number;supplierBalance:number;
}

export function ReportsSection(){
 const [from,setFrom]=useState(daysAgoISO(30)); const [to,setTo]=useState(todayISO()); const [applied,setApplied]=useState({from:daysAgoISO(30),to:todayISO()}); const [tab,setTab]=useState<Tab>('overview'); const [preview,setPreview]=useState<{title:string;html:string}|null>(null)
 const q=useQuery<Report>({queryKey:['reports',applied],queryFn:async()=>{const r=await fetch(`/api/reports?from=${applied.from}&to=${applied.to}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'فشل تحميل التقرير');return j}})
 const data=q.data; const salesTrend=useMemo(()=>data?.dailyTrend?.map(x=>({...x,label:x.date.slice(5)}))||[],[data])
 const metricCards: Array<{title:string; value:string; Icon:LucideIcon}> = [
   {title:'صافي المبيعات', value:money(data?.netSales), Icon:TrendingUp},
   {title:'تكلفة المبيعات', value:money(data?.cogs), Icon:Package},
   {title:'الربح الإجمالي', value:money(data?.grossProfit), Icon:TrendingUp},
   {title:'المصروفات', value:money(data?.totalExpenses), Icon:WalletCards},
   {title:'الربح الصافي', value:money(data?.netProfit), Icon:WalletCards},
   {title:'الهامش الصافي', value:`${data?.profitMargin ?? 0}%`, Icon:BarChart3},
 ]
 function apply(){if(!from||!to)return toast.error('اختر الفترة');if(from>to)return toast.error('من تاريخ يجب أن يسبق إلى تاريخ');setApplied({from,to})}
 function preset(days:number){const f=days===0?todayISO():daysAgoISO(days-1);const t=todayISO();setFrom(f);setTo(t);setApplied({from:f,to:t})}
 function exportReport(kind:'xlsx'|'csv'){window.open(`/api/sync/report-export?from=${applied.from}&to=${applied.to}&format=${kind}`,'_blank');toast.success(`بدأ تصدير ${kind==='xlsx'?'Excel':'CSV'}`)}
 function escapeHtml(v:unknown){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as Record<string,string>)[c]||c)}
 function openPrintPreview(){if(!data)return;const rows=(data.dailyTrend||[]).map(r=>`<tr><td>${escapeHtml(r.date)}</td><td>${money(r.sales)}</td><td>${money(r.returns)}</td><td>${money(r.profit)}</td></tr>`).join('');const products=(data.bestSelling||[]).slice(0,30).map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.sku)}</td><td>${x.qty}</td><td>${money(x.revenue)}</td><td>${money(x.profit)}</td></tr>`).join('');const html=`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><style>body{font-family:Arial;margin:0;padding:20px;color:#111}.sheet{max-width:900px;margin:auto}h1{text-align:center}.meta{text-align:center;color:#666;font-size:12px}.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0}.kpi{border:1px solid #ddd;padding:10px}.kpi b{display:block;margin-top:4px;font-size:16px}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid #ddd;padding:7px;text-align:right;font-size:12px}th{background:#f5f5f5}@media print{@page{margin:8mm}}</style></head><body><div class="sheet"><h1>مركز التقارير</h1><div class="meta">${applied.from} إلى ${applied.to}</div><div class="kpis"><div class="kpi">صافي المبيعات<b>${money(data.netSales)}</b></div><div class="kpi">مجمل الربح<b>${money(data.grossProfit)}</b></div><div class="kpi">صافي الربح<b>${money(data.netProfit)}</b></div></div><h3>المبيعات اليومية</h3><table><thead><tr><th>التاريخ</th><th>المبيعات</th><th>المرتجعات</th><th>الربح</th></tr></thead><tbody>${rows}</tbody></table><h3>الأصناف الأكثر مبيعًا</h3><table><thead><tr><th>الصنف</th><th>SKU</th><th>الكمية</th><th>الإيراد</th><th>الربح</th></tr></thead><tbody>${products}</tbody></table></div></body></html>`;setPreview({title:'تقرير المبيعات',html})}
 return <div className="space-y-5 pb-24">
   <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">مركز التقارير</h2><p className="text-sm text-muted-foreground">كل مؤشرات البيع والربح والمخزون والمصروفات للفترة المختارة.</p></div><div className="flex flex-wrap gap-2"><Button onClick={openPrintPreview} variant="outline" disabled={!data}><Printer className="me-2 size-4"/>معاينة وطباعة</Button><Button onClick={()=>exportReport('xlsx')} variant="outline"><FileSpreadsheet className="me-2 size-4"/>Excel</Button><Button onClick={()=>exportReport('csv')} variant="outline"><Download className="me-2 size-4"/>CSV</Button></div></div>
   <Card><CardContent className="flex flex-wrap items-end gap-2 p-4"><div><label className="text-xs">من</label><Input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 h-11"/></div><div><label className="text-xs">إلى</label><Input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 h-11"/></div><Button className="h-11" onClick={apply} disabled={q.isFetching}><RefreshCw className={q.isFetching?'animate-spin':''}/> تطبيق</Button><Button variant="outline" className="h-11" onClick={()=>preset(0)}>اليوم</Button><Button variant="outline" className="h-11" onClick={()=>preset(7)}>7 أيام</Button><Button variant="outline" className="h-11" onClick={()=>preset(30)}>30 يوم</Button><Badge variant="outline" className="h-11 rounded-xl px-4">{applied.from} → {applied.to}</Badge></CardContent></Card>
   <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{metricCards.map(({title,value,Icon})=><Card key={title}><CardContent className="p-4"><div className="flex items-center justify-between gap-2"><small className="text-muted-foreground">{title}</small><Icon className="size-4 text-primary"/></div><div className="mt-2 text-lg font-black">{value}</div></CardContent></Card>)}</div>
   <div className="flex flex-wrap gap-2 no-print">{([['overview','نظرة عامة'],['sales','المبيعات'],['products','الأصناف'],['inventory','المخزون'],['finance','المالية']] as [Tab,string][]).map(([k,l])=><Button key={k} variant={tab===k?'default':'outline'} onClick={()=>setTab(k)}>{l}</Button>)}</div>
   {q.isLoading?<Card><CardContent className="p-10 text-center">جاري تحميل التقرير...</CardContent></Card>:q.isError?<Card><CardContent className="p-10 text-center text-destructive">تعذر تحميل التقرير — {q.error instanceof Error?q.error.message:'خطأ'}</CardContent></Card>:data&&<>
    {tab==='overview'&&<div className="grid gap-4 lg:grid-cols-[1.65fr_1fr]"><Card><CardHeader><CardTitle>حركة المبيعات والربح</CardTitle></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={salesTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(v:number)=>money(v)}/><Area type="monotone" dataKey="sales" name="المبيعات" fill="currentColor" fillOpacity={0.12} stroke="currentColor"/><Area type="monotone" dataKey="profit" name="الربح" fill="currentColor" fillOpacity={0.05} stroke="currentColor"/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>طرق الدفع</CardTitle></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={(data.salesByMethod||[]).map(x=>({...x,label:paymentMethodLabel(x.name)}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(v:number)=>money(v)}/><Bar dataKey="value" name="القيمة" fill="currentColor" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card></div>}
    {tab==='sales'&&<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>المبيعات اليومية</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-right">التاريخ</th><th className="p-2 text-right">المبيعات</th><th className="p-2 text-right">المرتجعات</th><th className="p-2 text-right">الربح</th></tr></thead><tbody>{data.dailyTrend.map(r=><tr key={r.date} className="border-b"><td className="p-2">{r.date}</td><td className="p-2">{money(r.sales)}</td><td className="p-2">{money(r.returns)}</td><td className="p-2 font-bold">{money(r.profit)}</td></tr>)}</tbody></table></div></CardContent></Card><Card><CardHeader><CardTitle>المبيعات حسب التصنيف</CardTitle></CardHeader><CardContent className="space-y-2">{data.salesByCategory.map(x=><div key={x.name} className="flex justify-between rounded-xl border p-3"><span>{x.name}</span><b>{money(x.value)}</b></div>)}</CardContent></Card></div>}
    {tab==='products'&&<Card><CardHeader><CardTitle>الأصناف الأكثر مبيعًا</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-right">الصنف</th><th className="p-2 text-right">SKU</th><th className="p-2 text-right">الكمية</th><th className="p-2 text-right">الإيراد</th><th className="p-2 text-right">الربح</th></tr></thead><tbody>{data.bestSelling.map(x=><tr key={x.id} className="border-b"><td className="p-2 font-bold">{x.name}</td><td className="p-2 font-mono">{x.sku}</td><td className="p-2">{x.qty}</td><td className="p-2">{money(x.revenue)}</td><td className="p-2 font-bold">{money(x.profit)}</td></tr>)}</tbody></table></div></CardContent></Card>}
    {tab==='inventory'&&<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>ملخص المخزون الحالي</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3">{[['عدد المتغيرات',data.inventory.variants],['قيمة التكلفة',money(data.inventory.cost_value)],['قيمة البيع',money(data.inventory.retail_value)],['الربح المحتمل',money(data.inventory.potential_profit)],['منخفض',data.inventory.low_stock],['نافد',data.inventory.out_of_stock]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-muted/40 p-3"><small>{k}</small><div className="mt-1 font-black">{String(v)}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>الأرصدة</CardTitle></CardHeader><CardContent className="space-y-2"><div className="flex justify-between rounded-xl border p-3"><span>رصيد العملاء</span><b>{money(data.customerBalance)}</b></div><div className="flex justify-between rounded-xl border p-3"><span>رصيد الموردين</span><b>{money(data.supplierBalance)}</b></div></CardContent></Card></div>}
    {tab==='finance'&&<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>المصروفات حسب التصنيف</CardTitle></CardHeader><CardContent className="space-y-2">{data.expensesByCategory.length?data.expensesByCategory.map((x,i)=><div key={`${x.category}-${x.type}-${i}`} className="flex justify-between rounded-xl border p-3"><span>{x.category} <small className="text-muted-foreground">· {x.type}</small></span><b>{money(x.total)}</b></div>):<div className="p-6 text-center text-muted-foreground">لا توجد مصروفات للفترة.</div>}</CardContent></Card><Card><CardHeader><CardTitle>معادلة الربح</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><div className="flex justify-between"><span>صافي المبيعات</span><b>{money(data.netSales)}</b></div><div className="flex justify-between"><span>− تكلفة المبيعات</span><b>{money(data.cogs)}</b></div><div className="flex justify-between border-t pt-2"><span>الربح الإجمالي</span><b>{money(data.grossProfit)}</b></div><div className="flex justify-between"><span>− المصروفات</span><b>{money(data.totalExpenses)}</b></div><div className="flex justify-between border-t pt-2 text-base"><span>الربح الصافي</span><b>{money(data.netProfit)}</b></div></CardContent></Card></div>}
   </>}
   <PrintPreviewDialog open={!!preview} title={preview?.title||'معاينة'} html={preview?.html||''} onOpenChange={open=>!open&&setPreview(null)} />
   <style>{`@media print{body{background:#fff!important}}`}</style>
 </div>
}
