import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { openNumericPad } from '@/components/numeric-pad'
import { CheckCircle2 } from 'lucide-react'
import { formatEGP } from '@/lib/format'

export type ShiftReport = { invoiceCount:number; cashSales:number; cardSales:number; transferSales:number; creditSales:number; customerCash:number; cashRefunds:number; openingFloat:number; expectedCash:number; closingFloat:number; difference:number; totalSales:number; cashIn?:number; cashOut?:number; expenses?:number; openedAt?:string; closedAt:string }

type Props = { openShift?: { cashSales?:number; cardSales?:number; transferSales?:number }|null; open:boolean; close:boolean; report:ShiftReport|null; pin:string; openingFloat:number; closingFloat:number; notes:string; openMutation:{isPending:boolean;mutate:()=>void}; closeMutation:{isPending:boolean;mutate:()=>void}; setOpen:(v:boolean)=>void; setClose:(v:boolean)=>void; setReport:(v:ShiftReport|null)=>void; setPin:(v:string)=>void; setOpeningFloat:(v:number)=>void; setClosingFloat:(v:number)=>void; setNotes:(v:string)=>void }

export function ShiftDialogs({openShift,open,close,report,pin,openingFloat,closingFloat,notes,openMutation,closeMutation,setOpen,setClose,setReport,setPin,setOpeningFloat,setClosingFloat,setNotes}:Props){
 return <>
  <Dialog modal={false} open={open} onOpenChange={v=>!openMutation.isPending&&setOpen(v)}><DialogContent><DialogHeader><DialogTitle>فتح الوردية</DialogTitle><DialogDescription>أدخل رصيد البداية وPIN المستخدم لبدء البيع.</DialogDescription></DialogHeader><div className="space-y-3"><div><Label>رصيد البداية</Label><button type="button" className="flex h-12 w-full items-center justify-center rounded-xl border bg-background text-xl font-black" onClick={()=>openNumericPad({value:String(openingFloat),title:'رصيد بداية الوردية',min:0,decimal:true,onCommit:v=>setOpeningFloat(Number(v)||0)})}>{formatEGP(openingFloat)} ج.م</button></div><div><Label>PIN الكاشير</Label><button type="button" className="flex h-12 w-full items-center justify-center rounded-xl border bg-background text-xl font-black tracking-[0.5em]" onClick={()=>openNumericPad({value:pin,title:'PIN فتح الوردية',decimal:false,maxLength:4,onCommit:setPin,password:true})}>{pin?'•'.repeat(pin.length):'أدخل PIN من 4 أرقام'}</button></div><div><Label>ملاحظات</Label><Input value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>إلغاء</Button><Button onClick={openMutation.mutate} disabled={openMutation.isPending||pin.length!==4}>{openMutation.isPending?'جارٍ الفتح...':'فتح الوردية'}</Button></DialogFooter></DialogContent></Dialog>
  <Dialog modal={false} open={close} onOpenChange={v=>!closeMutation.isPending&&setClose(v)}><DialogContent><DialogHeader><DialogTitle>إغلاق الوردية</DialogTitle><DialogDescription>أدخل النقد الفعلي في الدرج وسيحسب النظام الفرق تلقائيًا.</DialogDescription></DialogHeader><div className="space-y-3">{openShift&&<div className="grid grid-cols-3 gap-2 rounded-xl bg-muted p-3 text-center text-xs"><div>نقدي<b className="block text-sm">{formatEGP(openShift.cashSales||0)}</b></div><div>بطاقة<b className="block text-sm">{formatEGP(openShift.cardSales||0)}</b></div><div>تحويل<b className="block text-sm">{formatEGP(openShift.transferSales||0)}</b></div></div>}<div><Label>النقد الفعلي في الدرج</Label><button type="button" className="flex h-12 w-full items-center justify-center rounded-xl border bg-background text-xl font-black" onClick={()=>openNumericPad({value:String(closingFloat),title:'النقد الفعلي في الدرج',min:0,decimal:true,onCommit:v=>setClosingFloat(Number(v)||0)})}>{formatEGP(closingFloat)} ج.م</button></div><div><Label>PIN الكاشير</Label><button type="button" className="flex h-12 w-full items-center justify-center rounded-xl border bg-background text-xl font-black tracking-[0.5em]" onClick={()=>openNumericPad({value:pin,title:'PIN إغلاق الوردية',decimal:false,maxLength:4,onCommit:setPin,password:true})}>{pin?'•'.repeat(pin.length):'أدخل PIN من 4 أرقام'}</button></div><div><Label>ملاحظات</Label><Input value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setClose(false)}>إلغاء</Button><Button variant="destructive" onClick={closeMutation.mutate} disabled={closeMutation.isPending||pin.length!==4}>{closeMutation.isPending?'جارٍ الإغلاق...':'تأكيد إغلاق الوردية'}</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!report} onOpenChange={v=>!v&&setReport(null)}><DialogContent><DialogHeader><DialogTitle>تقرير الوردية</DialogTitle></DialogHeader>{report&&<div className="grid grid-cols-2 gap-2 rounded-2xl border p-4 text-sm">{[['الفواتير',report.invoiceCount],['إجمالي المبيعات',formatEGP(report.totalSales)+' ج.م'],['نقدي',formatEGP(report.cashSales)+' ج.م'],['بطاقة',formatEGP(report.cardSales)+' ج.م'],['تحويل',formatEGP(report.transferSales)+' ج.م'],['آجل',formatEGP(report.creditSales)+' ج.م'],['المتوقع',formatEGP(report.expectedCash)+' ج.م'],['الفعلي',formatEGP(report.closingFloat)+' ج.م'],['الفرق',formatEGP(report.difference)+' ج.م']].map(([k,v])=><div key={String(k)} className="rounded-xl bg-muted p-3"><small>{k}</small><b className="block">{v}</b></div>)}</div>}<Button type="button" className="mt-3 w-full" onClick={()=>setReport(null)}><CheckCircle2/> تم</Button></DialogContent></Dialog>
 </>
}
