import { v4 as uuid } from 'uuid'
import { query, run, withTransaction } from '../db/client'
import { enqueueSync } from '../sync/queue'
import { mapEntity } from '../sync/mapper'
import type { PaymentMethod } from '../types'
import { addCustomerCredit, addSupplierDebit, addCash } from '../accounting'

export async function recordCustomerPayment(input:{userId:string;customerId:string;amount:number;method?:PaymentMethod;notes?:string;registerSessionId?:string|null;idempotencyKey?:string}){
 if(input.amount<=0)throw new Error('قيمة الدفعة يجب أن تكون أكبر من صفر')
 if(input.method==='cash' && !input.registerSessionId) throw new Error('يلزم وجود وردية مفتوحة للتحصيل النقدي')
 return withTransaction(db=>{const c=query<{balance:number}>(db,'SELECT balance FROM customers WHERE id=?',[input.customerId])[0];if(input.idempotencyKey){const prior=query<any>(db,'SELECT id FROM customer_payments WHERE idempotency_key=? LIMIT 1',[input.idempotencyKey])[0];if(prior)return {id:prior.id,balance:Number(c?.balance||0)}}if(!c)throw new Error('العميل غير موجود');if(input.amount>c.balance)throw new Error('الدفعة أكبر من رصيد العميل');const id=uuid();run(db,`INSERT INTO customer_payments(id,customer_id,amount,method,notes,idempotency_key) VALUES(?,?,?,?,?,?)`,[id,input.customerId,input.amount,input.method??'cash',input.notes??null,input.idempotencyKey??null]);run(db,"UPDATE customers SET balance=balance-?,updated_at=datetime('now') WHERE id=?",[input.amount,input.customerId]); addCustomerCredit(db,input.customerId,input.amount,'payment',id,'تحصيل من العميل'); if(input.method==='cash'&&input.registerSessionId) addCash(db,{sessionId:input.registerSessionId,userId:input.userId,type:'CUSTOMER_PAYMENT',referenceType:'customer_payment',referenceId:id,amountIn:input.amount,note:'تحصيل نقدي من عميل'});run(db,`INSERT INTO audit_logs(id,user_id,action,entity,entity_id,after_json) VALUES(?,?,?,?,?,?)`,[uuid(),input.userId,'CREATE','customer_payment',id,JSON.stringify({amount:input.amount,customerId:input.customerId})]);enqueueSync(db,{entityType:'customer_payment',entityId:id,operation:'create',payload:mapEntity(db,'customer_payment',id)});return {id,balance:c.balance-input.amount}})
}

export async function recordSupplierPayment(input:{userId:string;supplierId:string;amount:number;method?:PaymentMethod;notes?:string;registerSessionId?:string|null;idempotencyKey?:string}){
 if(input.amount<=0)throw new Error('قيمة الدفعة يجب أن تكون أكبر من صفر')
 if(input.method==='cash' && !input.registerSessionId) throw new Error('يلزم وجود وردية مفتوحة للدفع النقدي')
 return withTransaction(db=>{const s=query<{balance:number}>(db,'SELECT balance FROM suppliers WHERE id=?',[input.supplierId])[0];if(input.idempotencyKey){const prior=query<any>(db,'SELECT id FROM supplier_payments WHERE idempotency_key=? LIMIT 1',[input.idempotencyKey])[0];if(prior)return {id:prior.id,balance:Number(s?.balance||0)}}if(!s)throw new Error('المورد غير موجود');if(input.amount>s.balance)throw new Error('الدفعة أكبر من رصيد المورد');const id=uuid();run(db,`INSERT INTO supplier_payments(id,supplier_id,amount,method,notes,idempotency_key) VALUES(?,?,?,?,?,?)`,[id,input.supplierId,input.amount,input.method??'cash',input.notes??null,input.idempotencyKey??null]);run(db,"UPDATE suppliers SET balance=balance-?,updated_at=datetime('now') WHERE id=?",[input.amount,input.supplierId]); addSupplierDebit(db,input.supplierId,input.amount,'payment',id,'دفعة للمورد'); if(input.method==='cash'&&input.registerSessionId) addCash(db,{sessionId:input.registerSessionId,userId:input.userId,type:'SUPPLIER_PAYMENT',referenceType:'supplier_payment',referenceId:id,amountOut:input.amount,note:'دفع نقدي للمورد'});run(db,`INSERT INTO audit_logs(id,user_id,action,entity,entity_id,after_json) VALUES(?,?,?,?,?,?)`,[uuid(),input.userId,'CREATE','supplier_payment',id,JSON.stringify({amount:input.amount,supplierId:input.supplierId})]);enqueueSync(db,{entityType:'supplier_payment',entityId:id,operation:'create',payload:mapEntity(db,'supplier_payment',id)});return {id,balance:s.balance-input.amount}})
}
