import { getDb, query, run, withTransaction } from '../db/client'
import { v4 as uuid } from 'uuid'
import type { RegisterSession } from '../types'
import { enqueueSync } from '../sync/queue'
import { cashExpected } from '../accounting'

export async function getOpenSession(userId:string):Promise<RegisterSession|null>{const db=await getDb();return query<RegisterSession>(db,"SELECT * FROM register_sessions WHERE user_id=? AND status='open' ORDER BY opened_at DESC LIMIT 1",[userId])[0]??null}
export async function openSession(userId:string,openingFloat:number){if(openingFloat<0)throw new Error('الرصيد الافتتاحي غير صحيح');return withTransaction(db=>{if(!query(db,"SELECT id FROM register_sessions WHERE user_id=? AND status='open' LIMIT 1",[userId])[0]){const id=uuid();run(db,"INSERT INTO register_sessions(id,user_id,opening_float,status) VALUES(?,?,?,'open')",[id,userId,openingFloat]);run(db,`INSERT INTO audit_logs(id,user_id,action,entity,entity_id,after_json) VALUES(?,?,?,?,?,?)`,[uuid(),userId,'OPEN','register_session',id,JSON.stringify({openingFloat})]);enqueueSync(db,{entityType:'register_session',entityId:id,operation:'open',payload:{id,openingFloat,userId}});return query<RegisterSession>(db,'SELECT * FROM register_sessions WHERE id=?',[id])[0]}throw new Error('لديك وردية مفتوحة بالفعل')})}
export async function closeSession(id:string,closingFloat:number){if(closingFloat<0)throw new Error('النقد الفعلي غير صحيح');return withTransaction(db=>{const session=query<{id:string;user_id:string;opening_float:number}>(db,"SELECT id,user_id,opening_float FROM register_sessions WHERE id=? AND status='open'",[id])[0];if(!session)throw new Error('الوردية غير موجودة أو مغلقة');const sales=query<{cash:number}>(db,"SELECT COALESCE(SUM(CASE WHEN payment_method='cash' AND status='completed' THEN total ELSE 0 END),0) cash FROM sales WHERE register_session_id=?",[id])[0]?.cash??0;const returns=query<{cash:number}>(db,"SELECT COALESCE(SUM(CASE WHEN COALESCE(refund_method,'cash')='cash' AND status='completed' THEN total ELSE 0 END),0) cash FROM sale_returns sr JOIN sales s ON s.id=sr.sale_id WHERE s.register_session_id=?",[id])[0]?.cash??0;const expenses=query<{amount:number}>(db,"SELECT COALESCE(SUM(amount),0) amount FROM expenses WHERE register_session_id=?",[id])[0]?.amount??0;const ledgerExpected=cashExpected(db,id); const expected=ledgerExpected-(expenses||0);const difference=closingFloat-expected;run(db,"UPDATE register_sessions SET closing_float=?,expected_cash=?,difference=?,status='closed',closed_at=datetime('now') WHERE id=?",[closingFloat,expected,difference,id]);run(db,`INSERT INTO audit_logs(id,user_id,action,entity,entity_id,after_json) VALUES(?,?,?,?,?,?)`,[uuid(),session.user_id,'CLOSE','register_session',id,JSON.stringify({closingFloat,expected,difference})]);enqueueSync(db,{entityType:'register_session',entityId:id,operation:'close',payload:{id,closingFloat,expected,difference}});return {id,closingFloat,expected,difference}})}
